# Generated by Django 5.1.3 on 2024-11-05 21:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TodoList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='todolists', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('task_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('status', models.CharField(choices=[('uncompleted', 'Uncompleted'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='uncompleted', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('todolist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='todos', to='tasklist.todolist')),
            ],
        ),
    ]
